@startuml class

class Engine {
    - engine_type: string
    - potency: int
    - weight: float
}

class Vehicle {
    - vehicle_type: string
    - chassis: string
    - model: string
    - gas_consumption: float
    - year: int
    - engine: Engine
    + calculate_gas_consumption(): float
}

class Car {
    - num_doors: int
}

class Truck {
    - payload_capacity: float
}

class Yacht {
    - length: float
}

class Motorcycle {
    - num_wheels: int
}

class EngineCatalog {
    + add_engine(): void
}

class VehicleCatalog {
    + add_vehicle(): void
}

Vehicle --|> Engine
Car --|> Vehicle
Truck --|> Vehicle
Yacht --|> Vehicle
Motorcycle --|> Vehicle
EngineCatalog --|> Engine
VehicleCatalog --|> Vehicle

@enduml
