@startuml Buyer_ad

start
:Browse Suppliers;
:View Product Catalogs;
:Contact Supplier;
if (Satisfied) then (yes)
  :Negotiate Terms;
  :Finalize Deal;
  :Place Order;
  :Arrange Payment;
  :Receive Products;
elseif (Add Vehicle or Engine) then
  :Select option to add vehicle or engine;
  if (Option == Add Vehicle) then (yes)
    :Provide vehicle details;
    :System validates and adds vehicle to catalog;
  elseif (Option == Add Engine) then (no)
    :Provide engine details;
    :System validates and adds engine to catalog;
  else
    :Display error message;
  endif
else (no)
  stop
endif

@enduml
